on:
  push:
    tags:
    - '*'

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2

    - name: Build policy
      id: aserto-build
      uses: aserto-dev/aserto-build-action@v1-beta
      with:
        source: "src"
        target: "build/bundle.tar.gz"
        options: "--revision $GITHUB_SHA"

    - name: Draft Release
      id: draft_release
      uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "build/bundle.tar.gz"
        tags: true
        draft: true
        verbose: true

    - name: Publish Release
      id: publish_release
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.draft_release.outputs.release_id }}
