on:
  push:
    tags:
    - '*'

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2

    - name: build-bundle 
      id: aserto-build
      uses: aserto-dev/aserto-build-action@v1-beta
      with:
        source: "src"
        target: "build/bundle.tar.gz"
        options: "--revision $GITHUB_SHA"

    - name: draft_release
      uses: release-drafter/release-drafter@v5
      with:
        name: "${{ github.ref }}"
        tag: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: upload_assets
      uses: AButler/upload-release-assets@v2.0
      with:
        release-tag: ${{ github.ref }}
        files: 'build/bundle.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: publish_release
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
