on:
  push:
    tags:
    - '*'

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2

    - name: Build policy
      id: aserto-build
      uses: aserto-dev/aserto-build-action@v1-beta
      with:
        source: "src"
        target: "build/bundle.tar.gz"
        options: "--revision $GITHUB_SHA"

    - name: Read Tag
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Draft Release
      id: draft_release
      uses: release-drafter/release-drafter@v5
      with:
        name: "${{ steps.get_tag.outputs.tag }}"
        tag: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Assets
      id: upload_assets
      uses: AButler/upload-release-assets@v2.0
      with:
        release-tag: ${{ steps.get_tag.outputs.tag }}
        files: 'build/bundle.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Release
      id: publish_release
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
