on:
  push:
    tags:
    - '*'

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2

    - name: build-bundle 
      id: aserto-build
      uses: aserto-dev/aserto-build-action@v1-beta
      with:
        source: "src"
        target: "build/bundle.tar.gz"
        options: "--revision $GITHUB_SHA"

    - name: upload
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/bundle.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "Aserto bundle release"
        omitBody: true
